import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/index";

export const metadata = {
  title: "desgy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-scroll="0">
      <body className="bg-black text-[#ffffffe6]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
